"""empty message

Revision ID: aee185ea09a5
Revises: 
Create Date: 2023-05-31 17:29:17.191567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee185ea09a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cur_name', sa.String(), nullable=False),
    sa.Column('cur_shortcut', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('cur_to_eur', sa.Float(), nullable=False),
    sa.Column('eur_to_cur', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cur_name'),
    sa.UniqueConstraint('cur_shortcut')
    )
    op.create_table('user_log',
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency_in', sa.String(), nullable=False),
    sa.Column('currency_out', sa.String(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['user_log.exchange_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cur_shortcut', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['user_log.exchange_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('history')
    op.drop_table('user_log')
    op.drop_table('currencies')
    # ### end Alembic commands ###
